// This file is generated by scripts/generate-seo-route-manifest.mjs.
// Do not edit this route list manually; it is refreshed before every production build.
export const INDEXABLE_ROUTE_PATHS = [
  "/",
  "/about",
  "/booking",
  "/contact",
  "/corporate-commercial-disputes",
  "/en",
  "/en/about",
  "/en/contact",
  "/en/corporate-commercial-disputes",
  "/en/international",
  "/en/services",
  "/en/uae-asset-debt-recovery",
  "/international",
  "/services",
  "/uae-asset-debt-recovery",
] as const;
