// This file is generated by scripts/generate-seo-route-manifest.mjs.
// Do not edit this route list manually; it is refreshed before every production build.
export const INDEXABLE_ROUTE_PATHS = [
  "/",
  "/about",
  "/booking",
  "/contact",
  "/insights",
  "/international",
  "/iran-uae-commercial-disputes",
  "/services",
  "/uae-asset-debt-recovery",
] as const;
